# index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
app:
    resource: '../src/Controller/'
    type: annotation
    prefix: /api
    defaults:
        _format: json
        _locale: en
